### ISSUE TITLE
Improve styling on the "Last Incident Report" card (landing)

### ISSUE THREAD

**Issue by clari182** [responsible-ai-collaborative/aiid#1123]
- Improve "Last Incident Report" card
- Its header should be inside a container but without having 2 nested cards 

### Current:
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/4105289/191350134-b6275a99-e216-4cd8-9846-ad86f17a1b05.png">

### Option 1 - Header inside card
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/4105289/191351748-d7bd424c-c4b6-4b82-8716-b75978f1b2fa.png">

### Option 2 - Highlighted header
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/4105289/191352486-282985a4-bc24-44ed-ae35-57eccf4ad0dd.png">

### Option 3 - Label like header
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/4105289/191354048-63933c0e-0c20-4ba8-9bd1-cffe7b876da5.png">

**Comment by clari182** [comment]
Hey @lmcnulty @smcgregor I'd love your input on this. 
Above you can see 3 options that would improve the Last Incident Report card. Let me know if you have a preference or if you want to propose other options. Thanks!

**Comment by smcgregor** [comment]
I would go with option 1 here. Some of the others could be good as well, but I don't like the use of the badge-like styling for the header since users may think it is clickable rather than a header. The positioning of option 1 is also the most universal since option 3 does not work for cards that don't have an image in the upper left.
