### ISSUE TITLE
Promote form submission fields `developer`, `deployer` and `harmed` are required but hidden

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#1161]
## Steps to reproduce

1. Go to `/apps/submitted`
2. Edit a pending submission **without** an incident ID associated
3. Fill the `Incident ID` with a valid incident ID
4. The `developer`, `deployer`, and `harmed` fields are hidden and they are impossible to fill them
5. The `Update` form button is disabled because these 3 fields are required

### Fields are visible if Incident ID is not set

![image](https://user-images.githubusercontent.com/6564809/192598171-d2350a81-7ea0-4d48-bf7e-77c919bd81e5.png)

### Fields are hidden if Incident ID is set

![image](https://user-images.githubusercontent.com/6564809/192598721-90a3578c-cf7f-4ba2-bdb3-faf7df4dbc6c.png)

PR #1166

**Comment by LKchemposer** [comment]
In this case, these fields should be hidden, but auto-filled per `incident id`, so that users don't overwrite the incident metadata for these. @smcgregor, thoughts?

Along the same line, please also hide these (and also auto-filled) when `incident id` is assigned in the `Edit Submission` window per #1111

**Comment by smcgregor** [comment]
Presenting the current values for an existing incident helps provide context in the review queue, but it would probably need to be a DB query then from the foreign key, rather than present the values as they sit in the submitted queue.
