### ISSUE TITLE
Landing page – awkward line split for the welcome text

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1189]
I love the new landing page! I find that it feels so much more welcoming, and clean!

However, the welcome text is a bit awkward as it reads as "welcome to the artificial" and "intelligence incident database". If possible, it should read as "welcome to the" "artificial intelligence incident database" or "welcome to" "the artificial intelligence incident database".

The "welcome to (the)" can also be a smaller size to accentuate the "AI incident database" part, but this is more of a design choice, and i am not a designer, so i might not know what i'm talking about.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/39468345/193208995-bc16aeb3-6cec-405b-8900-f3456f783a2b.png">

**Comment by lmcnulty** [comment]
I think it looks bad if the first line is longer than second, because small things naturally rest on larger ones rather than the reverse.

![image](https://user-images.githubusercontent.com/25443411/193303503-a8987702-be59-4118-8084-a6904ac7007c.png)

If we shorted "artificial intelligence" to "AI" and perhaps for clarity changed the desktop search bar to use the full term, we could have the second line be longer and fit the whole noun phrase, possibly in addition to lightening "Welcome to the"

![image](https://user-images.githubusercontent.com/25443411/193305937-6525e9ad-6843-4349-99cf-b4970c30bbd7.png)

**Comment by cesarvarela** [comment]
+1 second option

**Comment by smcgregor** [comment]
+1 second option as well

**Comment by LKchemposer** [comment]
+1 second option
