### ISSUE TITLE
Some docs in candidates collection are missing fields

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1241]
Some look like this:

![image](https://user-images.githubusercontent.com/1172479/194966632-a94370dc-284f-4cc1-b578-a6a3267d337c.png)

some like this:

![image](https://user-images.githubusercontent.com/1172479/194966666-50cd0e2f-24df-407d-9b69-74b07c83efc4.png)

This prevents this query from executing:

![image](https://user-images.githubusercontent.com/1172479/194966745-5974b047-2e85-49d8-95ec-889ce7dde799.png)

@lmcnulty should I delete the ones that are missing those fields? Will this happen again?

**Comment by lmcnulty** [comment]
It's supposed to look like that. When an article isn't a match, we store the url so that we know not to scrape it and hit the NLP API again. I also included the title because it's not much more data and I thought it could be useful for debugging. But everything else is dropped, because we can't store the full text of every article we scrape.

Which query is it that's failing?

My current guess is that a *matching* article [ended up with a null date](https://github.com/responsible-ai-collaborative/nlp-monitoring/blob/main/fetch-news.py#L85), and Mongo allowed us to insert it but not to query it. Do you get anything when you query `{ match: true, date_published: null }` in the Mongo UI?

**Comment by cesarvarela** [comment]
You can see it here: 

https://staging-aiid.netlify.app/apps/newsSearch/

and  the read-only staging connection string if you want to play around with Compass or something like that:

mongodb+srv://readonly:vNMlVM35rsTlMUTr@aiiddev.seam4.mongodb.net

**Comment by lmcnulty** [comment]
So indeed, there the entry with url `https://3d-diffusion.github.io/` has a null `date_published` :

<img width="400" src="https://user-images.githubusercontent.com/25443411/195172834-d4aa1f73-5f10-453f-8ad0-91d5558aaf02.png"/>

Weirdly, though, it's also null on my dev database, but is rendering in the deploy preview:

<img width="400" src="https://user-images.githubusercontent.com/25443411/195173198-e5b897bb-a0e5-45f2-afd1-5d187cedd598.png"/>

<img width="500" src="https://user-images.githubusercontent.com/25443411/195173365-cbf15f33-1b1a-4743-ac8b-9ca9fccc461c.png"/>

Can you try deleting that entry?

I'll make a pull request to [nlp-monitoring](https://github.com/responsible-ai-collaborative/nlp-monitoring) to skip items without published dates.

**Comment by cesarvarela** [comment]
It works now: https://staging-aiid.netlify.app/apps/newsSearch/

The same issue will happen on production, can you create a migration to remove all candidates with this same condition, please?

```
{date_published: {$exists: true, $eq: null}}
```

**Comment by cesarvarela** [comment]
Unrelated, but the camelCase URL looks weird to me 🐱

**Comment by lmcnulty** [comment]
The specific problem with dates was fixed shortly after this issue was opened. Better null handling in general is added by https://github.com/responsible-ai-collaborative/nlp-monitoring/pull/1.
