### ISSUE TITLE
Redesign similar incidents

### ISSUE THREAD

**Issue by clari182** [responsible-ai-collaborative/aiid#1251]
Redesign the similar incident section to use badges

### Current
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/4105289/195416871-481e0fc0-7e2a-41ce-b0cc-3d26ca3c16b6.png">

### Option 1: 
<img width="952" alt="image" src="https://user-images.githubusercontent.com/4105289/195416490-a71df445-09f2-4f5f-9885-1b6f29aed140.png">

### Option 2:
![image](https://user-images.githubusercontent.com/4105289/195416617-3fa5765f-116c-4e78-be42-fb1e4fc2ce00.png)

@smcgregor and @lmcnulty please let me know what option you like best and share your thoughts on the matter.

Thanks!

**Comment by lmcnulty** [comment]
- It's nice that it gives them more color, but I don't really understand how these components fit the meaning communicated by styling them as badges. Badges are usually small widgets attached to a larger UI element to indicate something about it, like the tags in our issue tracker:
  <img width="550" src="https://user-images.githubusercontent.com/25443411/195435279-84a7c736-67ca-422a-be1a-f7758c0471c6.png"/>
  I don't think the badge component was really intended to contain other UI elements like this, which is why, for example, there's missing vertical padding that almost lets the [Use #...] button touch the edge. It seems more like a card in this design. This might be a place to use the [generic incident/report cards](https://github.com/responsible-ai-collaborative/aiid/pull/1095) when that lands. We could perhaps also add the option to set different background colors for cards.
- I prefer the button group as a selector for mutually-exclusive options. To me it looks more like [real-life radio-buttons](https://en.wikipedia.org/wiki/Radio_button#/media/File:Car_Radio_of_Analog_Era.jpg) than `<input type="radio">` and has the same affordance. The lighter background looks much better than before.
- "Is this incident related" should go right before the choice of answers.
- I would keep it as "Use ID #…" rather than just "Use #." Actually, neither of those are great – I don't think it's that intuitive for a button in one part of the form to set the ID field in another part of the form. Removing "ID" obscures it further. It might be clearer what's being asked if we have a single mutually-exclusive selection of "Same Incident/Related/Unrelated/Not sure." Then maybe if "same incident" is chosen we could add a toast to indicate that it changed the ID.
- Sometimes there are a lot of matching results, and I think this design will use more vertical space. Since they appear between the form elements, it could be annoying if there are too many.

**Comment by clari182** [comment]
Yes, I agree with the Badges vs Cards. You're right, cards would be much more useful here as they are meant to contain more information/inner components.
I'll work on more designs based on your comments and put them on the task

**Comment by clari182** [comment]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/4105289/195656436-857eddeb-c179-4a9e-9bd5-1f3fbc156bf7.png">
<img width="952" alt="image" src="https://user-images.githubusercontent.com/4105289/195656497-c62a4efe-feee-405e-8a18-eb370aab23c4.png">
<img width="955" alt="image" src="https://user-images.githubusercontent.com/4105289/195656664-84a4a5ea-f545-473b-88d1-0e10f1ff8569.png">
<img width="956" alt="image" src="https://user-images.githubusercontent.com/4105289/195656891-4902b378-25a0-46b2-a77f-9219ffb403f4.png">

Here are more options using cards. Personally, I like the ones with a light background so it adds a little bit of color but let me know what you think @lmcnulty @smcgregor. Because it doesn't really follow our current card design, but since this is kind of a special case, I think it's applicable.

**Comment by smcgregor** [comment]
I think this is done with #1324, feel free to reopen if I missed something.
