### ISSUE TITLE
New Taxonomies Integration

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1497]
It is time to land CSET v2 and the GMF taxonomies in the web stack. Steps:

1. Remove the resources taxonomy entirely. We are not currently using it and it is better to re-introduce it after the CSETv2 and GMF taxonomies are integrated. This should be accomplished simply by removing the resources document from the taxa collection and removing the resources collection.
2. Copy the CSETv1 taxa document to a new schema in the taxa collection.
3. Update the schema to match the [v2 specification](https://docs.google.com/document/d/1SYJfiP_E_gya89ljxZumC9z6MkP4z1I-bfgnDs6kIhQ/edit#heading=h.ehpbfkrxkvv)
4. Update the taxonomy feature, which formerly put classifications for the CSET taxonomy into "classifications" and classifications for the resources taxonomy into "resources" so that all taxonomies place their classifications into the "classifications" collection. Taxonomies should be fully specified in the taxa collection and its data should be in the classifications collection.
5. The CSET v2 taxonomy should then be displayed on the citation pages and it should be possible to introduce new classifications which takes the taxonomy from hidden, to displayed.
6. At this point it should be pretty easy to add the GMF taxonomy after defining the form fields that go into the UI

**Comment by lmcnulty** [comment]
Currently, the `"classifications"` entry in the classifications schema is an object containing properties for each of the fields that exist in a schema.

```json
"classifications": {
  "bsonType": "object",
  "properties": {
    "AI Applications": {
      "bsonType": "array",
      "items": {
        "bsonType": "string"
      }
    },
    "AI System Description": {
      "bsonType": "string"
    },
    …
}
```

This means that to query classifications, we need a graphql query for each namespace which enumerates all of its possible keys.

```graphql
query FindCSETClassifications($query: ClassificationQueryInput) {
  classifications(query: $query) {
	_id
	incident_id
	notes
	namespace
	classifications {
          AIApplications
          AISystemDescription
          …
        }
    }
}
```

@smcgregor, you pointed out that this is a problem because it means we need to write new GraphQL specific to each new taxonomy we add.

It seems to me that as an alternative, we could make the `"classifications"` entry an array containing key-value pairs of of multiple types of data. This is not directly supported by MongoDB / Graphql. However, we could work around it by making the value of a classification an object with (optional) keys for each possible type. The schema would look something like this:

```json
"classifications": {
  "bsonType": "array",
  "items": {
    "bsonType": "object",
    "properties": {
      "name" : { "bsonType": "string" },
      "type" : { "bsonType": "string" },
      "value": {
        "bsonType": "object",
        "properties": {
          "string": { "bsonType": "string" },
          "bool": { "bsonType": "bool" },
          "string[]": { "bsonType": "array", "items": {"bsonType": "string"}}
        }
      }
    }
  }
}
```

This would allow us to write a query like:

```javascript
const { data: classificationsData } = useQuery(
  `query FindClassifications($query: ClassificationQueryInput) {
      classifications(query: $query) {
      _id
      incident_id
      notes
      namespace
      classifications
    }
  }`, 
  { variables: { query: { incident_id: incidentId } } }
);

classificationsData.classifications.forEach((classification) => {
  classification.classifications.forEach((c) => {
    console.log(classification.namespace, '-', c.name, '-', c.value[c.type]);
  })
})
```

Outputting something like

```
CSET - AI Applications - ["Direction suggestions", "recommendation engine"] 
CSET - AI System Description - Waze, a directions app meant to decide what…
…
```

Having a "type" key for entries in a strongly-typed database feels a little icky, but it seems like we've already crossed that threshold, since our taxa collection already has a `field_list.[].mongo_type` key.

---

Incidentally, I think it's confusing that the `classifications` collection has entries with a `classifications` key. If we're going to make a major schema change like this, I think we should also take the opportunity to rename the key.

**Comment by smcgregor** [comment]
This seems reasonable to me, but it is stretching my GraphQL/Mongo expertise. I am not sure if @pdcp1 or @cesarvarela are in the office at the moment to comment, but in the absence of other direction I think you can proceed along these lines.

**Comment by cesarvarela** [comment]
I like the overall approach, except I would serialize the `value` field, so it is always a `string.`

```
  classifications(query: $query) {
      _id
      incident_id
      notes
      namespace
      classifications {
         name
         type
         value 
      }
```

Both options have trade-offs. I'm more used to seeing values being serialized.

With this change, the `type` field might not be necessary since it is already specified in the `taxa` collection.
