### ISSUE TITLE
Report 1781 in Algolia Does Not Match Report 1781 in MongoDB

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1552]
It looks like it was likely fixed after ingestion and didn't update the index.

<img width="955" alt="Screen Shot 2023-01-17 at 10 46 58 PM" src="https://user-images.githubusercontent.com/64780/213103188-9a866a11-8ac9-4188-979b-ed55fb8af960.png">

<img width="331" alt="Screen Shot 2023-01-17 at 10 47 24 PM" src="https://user-images.githubusercontent.com/64780/213103204-ca4a2ca0-f642-4928-b64a-6e27a5a4e349.png">

**Comment by cesarvarela** [comment]
This is because `text` differs from `plain_text`, and we send `plain_text` to Algolia.

It happened because of either:

- text was modified directly on the DB
- something weird went on when saving from the UI, although we have many tests that check that `plain_text` is `text` unformatted

I think this is a one-time thing and should be fixed by editing and saving the report.

**Comment by smcgregor** [comment]
Report saved. Let's close this after confirming.

**Comment by cesarvarela** [comment]
It looks like it worked. Why it happened is still a mystery.
