### ISSUE TITLE
No Records Found in Algolia from GMF Taxonomy Click

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1607]
Click on `[Automatic Skill Assessment](https://deploy-preview-18--lmcnulty-staging.netlify.app/apps/discover/?classifications=GMF%3AKnown%20AI%20Goal%3AAutomatic%20Skill%20Assessment)` on the GMF taxonomy page and nothing comes up in the discover app.

https://deploy-preview-18--lmcnulty-staging.netlify.app/taxonomy/gmf/

**Comment by lmcnulty** [comment]
This occurs because my Algolia index only contains a subset of the entries (to fit in the free tier), and some of the classification values aren't on any of the Algolia entries. If you try [Autonomous Driving](https://deploy-preview-18--lmcnulty-staging.netlify.app/apps/discover/?classifications=GMF%3AKnown%20AI%20Goal%3AAutonomous%20Driving&display=details&is_incident_report=true&page=1) it works.
