### ISSUE TITLE
Citation Page Improvements

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1639]
* Move "Suggested citation format" content into the "Incident Stats" panel. It doesn't need its own panel
* Add the "Notify me of updates" button to the header in addition to the tools panel
* Move the "Reports Timeline" into the "Reports" section. It doesn't need to be as high on the page as it is.
* Any other look and feel improvements that may come up

**Comment by smcgregor** [comment]
@lmcnulty @clari182 please feel free to add to this change list. @clari182 can you work implementation when you clear your other items?

**Comment by Janetbananet** [comment]
Some other suggestions:

- Regarding the "Suggested Citation Format" (above): could we instead make this part of the "BibTex Citation" link in the "Tools" block? So the title of that link in the Tools Block would say "Citation Info" and the content would include both the "Suggested Citation Format" and the "BibTex Citation".
- Bump the "Tools" block up to just above the Description. As a user, I don't notice these tools when I start scrolling because by then I'm looking for the content itself.
- Size down the Carousel image block so it doesn't take up so much vertical space.

**Comment by smcgregor** [comment]
@Janetbananet  I am good with your suggested changes to the citation presentation. I would put the tools just below description, I am also good with sizing down the carousel if it looks good in the deploy preview.
