### ISSUE TITLE
Navigation triggers re-render of the "account" button in header

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1718]

**Comment by cesarvarela** [comment]
This happens because the Layout component is being mounted/unmounted on every navigation, but it is not that noticeable in production. It flickers a lot on deploy previews if the URL is not whitelisted.

Fixing it would require moving the Layout component to the `wrapPageElement` function and removing it from every page, which is a lot of work. I wonder if it is worth it.

**Comment by cesarvarela** [comment]
Oh, it is way more noticeable if you are logged in.
