### ISSUE TITLE
Rendering fallback image in the submission form

### ISSUE THREAD

**Issue by Janetbananet** [responsible-ai-collaborative/aiid#1799]
Background: Currently, when a user is entering an image URL into the submission form, the image preview automatically shows the fallback image if the URL from the original source does is not able to load. This will cause people to believe that the URL worked even in cases when it did not. 

Change needed: do not render the fallback image on the submission form unless the user elects to display the fallback by default.

**Comment by lmcnulty** [comment]
I think rather than hide the fallback image behind an option, it would be better to indicate failure while showing the fallback. For instance, by making the input box red and showing a message.

**Comment by smcgregor** [comment]
@lmcnulty do people need to see the fallback image? It seems like showing it adds confusion, or at least we have one case there.

**Comment by clari182** [comment]
I'd like to take this issue but I'm not sure what the preferred solution is. I think I agree more with @lmcnulty and showing the fallback is ok but adding a message under the input that states that it's a fallback. For example something like
`Image URL could not be loaded, using a fallback image` (with better wording).
Otherwise, the image would appear if correct and disappear if not and it could create some annoying user experience.

Also, I think if we don't show the fallback but let the user enter an invalid URL (or empty) it might seem like no image will be assigned to the incident and might force the user to put a random image URL that has nothing to do with the incident.

Let me know what you think and I can start working on this.

**Comment by smcgregor** [comment]
Sounds good to me.
