### ISSUE TITLE
Consider adding a Captcha to the Submit form

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1862]
I think we have our first spam submission 🥳 

![image](https://user-images.githubusercontent.com/1172479/231828870-65de57e1-72ca-4c71-8aea-6f014e97460f.png)

**Comment by lmcnulty** [comment]
We will probably need a captcha at some point, but I don't think this is spam. I think it's a good-faith attempt to document a problem with an AI system. It just doesn't match what we're doing with the submission form

**Comment by smcgregor** [comment]
@cesarvarela I agree with Luna. I think this is a first-party incident report where an image generator produced pornography for an innocent query.

**Comment by smcgregor** [comment]
We are going to index more rich media soon. Eventually we will need to adopt a policy for how to handle smut. I hope we avoid it for a bit longer, both because harm minimization of people that are non-consensually deepfaked means not increasing the associated deepfake's exposure and because I don't expect managing the data to be pleasant.

CC @LKchemposer @kateperk @Janetbananet
