### ISSUE TITLE
Add the Ability to Create Incidents without Reports

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#2040]
We will sometimes need to split a `/cite/##` page into multiple incidents, but we currently cannot create a new incident except by adding a new report. This issue is for creating a new incident (as an editor) then there is the ability to shift over an existing report.

**Comment by smcgregor** [comment]
Likely for you @pdcp1, probably not a big one.

**Comment by pdcp1** [comment]
@smcgregor What do you prefer? 
1. A `New Incident` button (somewhere) that creates an empty incident without any reports associated, 
2. or a `Clone Incident` button on the Cite page `/cite/##` that creates a new Incident preloaded with the same data (title, description, entities, etc) without any report associated?

I'm inclined to the second option, I think it's easier to clone and change some field values instead of filling everything again.

**Comment by smcgregor** [comment]
2 sounds good to me. We will likely eventually do 1 as well. Perhaps 1 would go here: https://incidentdatabase.ai/admin/

I would do 2 then 1 if it is not much more effort.

**Comment by pdcp1** [comment]
Closing this since it was already merged into Staging
