### ISSUE TITLE
DB Collection Versioning

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#2041]
We need some ability to record the history of collections through time so we can have an activity feed and rollback changes that were made in error. This issue is initially a design issue -- no implementation. We will figure out what is possible here with standard libraries and approaches then decide whether we implement this ourselves.

**Comment by smcgregor** [comment]
Maybe @pdcp1 on this one?

**Comment by pdcp1** [comment]
# DB Collection versioning

## Schema design

1. New `reports_history` collection with these fields:
    - `editor` (the user name which made the changes)
    - the rest of the fields from the `report`
      - including the `epoch_date_modified` that should include the full datetime, not just the day. (ie: `1685740426`)

2. New field `epoch_date_modified` field on the `incidents` collection, that should include the full datetime, not just the day. (ie: `1685740426`)

3. New `incidents_history` collection with these fields:
    - `editor` (the user name which made the changes)
    - the rest of the fields from the `incident`
      - including the `epoch_date_modified` that should include the full datetime, not just the day. (ie: `1685740426`)

## Code logic changes
To maintain the item's history we only need to save a copy of the item on the `xxxx_history` collection each time that the user does an update.
In the future, if we want to rollback to a specific item version, we can override the current item with the item from the `xxxx_history` collection.
With the schema presented above, we have all the information needed to display the changes between versions if that is needed in the UI. It could be a good feature to have. It could help editors to see what were the changed made.

## Migrations approach

For migrations that affect `reports` and `incidents` collections, we should update the `reports_history` and `incidents_history` respectively.
The migration for both collections will be really similar since both collections have the same fields. I don't anticipate a major complexity in future migrations.

@smcgregor @cesarvarela What do you think about this approach?

**Comment by smcgregor** [comment]
@cesarvarela want to take first crack?

**Comment by smcgregor** [comment]
This sounds good to me. In the future, we may want to compress the history collection by storing exclusively the delta/change in the records, but that would require a lot of additional mechanics to get right and we don't have anything needing compression.

**Comment by pdcp1** [comment]
@smcgregor When a user edits an incident, should we add that user to the incident `editors` list?
ie: Before the edition:
```
incident: {
  editors: [User A]
}
```

After `User B` made a change to the incident:
```
incident: {
  editors: [User A, User B]
}
```

**Comment by smcgregor** [comment]
Can they subsequently remove themselves? If so, this seems a reasonable time saver.

**Comment by pdcp1** [comment]
Closing this since it was already merged into Production
