### ISSUE TITLE
GMF:Potential AI Technology:Word NGram is an object instead of an array 

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#2088]
![image](https://github.com/responsible-ai-collaborative/aiid/assets/25443411/70ca1767-0714-42c6-951b-e39f88040d14)

![image](https://github.com/responsible-ai-collaborative/aiid/assets/25443411/7e9cf8a8-7f54-4658-bbac-257547c57de8)

**Comment by smcgregor** [comment]
High priority on this one, potentially critical depending on what is happening.

CC @clari182 @cesarvarela @pdcp1 @lmcnulty any claimants?

**Comment by cesarvarela** [comment]
@lmcnulty @smcgregor

It looks like the issue here is that a new item outside of the available options was entered. 

Should I prevent that? Or should I allow it?

In this case, `Word NGrams` is not in the Tags component `options` prop, so it adds a new one using this format: `{"customOption":true,"label":"Word NGrams","id":"new-id-1"}`.


![image](https://github.com/responsible-ai-collaborative/aiid/assets/1172479/ae7f1b38-048d-4806-a00f-a50b091b6610)

This is how it looks when you do it:

![image](https://github.com/responsible-ai-collaborative/aiid/assets/1172479/c3dda18d-d5d5-4c3d-ab79-7b1082a90272)

**Comment by smcgregor** [comment]
Yes, it should be possible to enter terms that have never been entered before.

**Comment by smcgregor** [comment]
@npit FYI a fix just landed for this (building now).

**Comment by cesarvarela** [comment]
This is happening everywhere a field of `display_type` `multi` is used:

<img width="784" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/b483ceb4-971e-4926-a55a-afa526bf5c9e">

I think we'll need a migration that transforms: `{"customOption":true,"label":"lidar sensors","id":"new-id-14"}` to `lidar sensors`, but please confirm @smcgregor @lmcnulty because I'm not that familiar with the classifications stuff.

**Comment by smcgregor** [comment]
@lmcnulty Can you comment? I am not sure here.

**Comment by lmcnulty** [comment]
@cesarvarela Yes, I think we will need a migration for items of `display_type: "multi"`. I'm not sure why the values became objects – I'm pretty sure before they were just strings.
