### ISSUE TITLE
Create and use default user for promoting submissions

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2240]
Currently, the logic that promotes submissions defaults to using Sean's user ID for the **editor** field if it's unset (it's been like this for a while; in the past it was just his name). To my knowledge/code search, no other place uses his user ID like this.

https://github.com/responsible-ai-collaborative/aiid/blob/418a34d7e3461a02e6f7d6af4c7ca8373f1f806a/site/realm/functions/promoteSubmissionToReport.js#L29

If we need to fallback to satisfy the expectation that every submission promoted to a report has an editor ID, we should create a default user with no permissions and substitute it there.

**Comment by pdcp1** [comment]
@kepae I need your help on this. In order to change this default user, we should create a new user manually from the **Production** Atlas UI: `App Services` > `App Users` > `Add New User`.
Fill in any email that you consider appropriate for a default user and a password.
After creating the user, filter the list by email and copy the user Id here.

Then, I will change the code to use that user.

**Comment by kepae** [comment]
Thanks for your patience, just confirmed the new account:

Default user:
email: `defaultuser at incidentdatabase dot ai`
_id: `65031f49ec066d7c64380f5c`

I'll add this to the wiki, perhaps in a "special public values" section.

**Comment by pdcp1** [comment]
Closing this since it was merged into Staging
