### ISSUE TITLE
Filter `publish == false` CSET taxonomy classifications from database snapshots

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2280]
Currently, the database snapshots dump the entire `aiidprod` database in our backup tool fork (https://github.com/responsible-ai-collaborative/mongodb-awesome-backup). There is a short-term request to remove unfinished taxonomy/classification data from the snapshot for CSET. Specifically, classification documents with `{publish: false}` should be removed from the database snapshots.

I believe this can be accomplished using the `mongodump` tool's `--query` option (or even better, `--queryFile`) to folter only these documents:
https://www.mongodb.com/docs/database-tools/mongodump/#std-option-mongodump.--query

There may be work to configure this with the backup tool.

**Comment by smcgregor** [comment]
We have snapshots and could have data products. The implication here is we need to start publishing data products rather than snapshots, but for operational purposes continue producing snapshots. They are important for backups and restoring development environments.

We are already sort of producing data products here: https://github.com/responsible-ai-collaborative/mongodb-awesome-backup/blob/master/bin/backup.sh#L53

Those produce CSV files that are packaged with the snapshots.

I recommend developing the export statements on your client and then opening a PR against that backup.sh script to produce the snapshots and data products together. From there, you separate the backup.sh script into two scripts that post to different AWS buckets when triggered from workflows. One is write-only with the ability to download backups from the AWS UI (snapshots) and the other is a public bucket that contains the data products and the historical snapshots (needs migrations).

**Comment by pdcp1** [comment]
Let me know if I understood correctly.

We should do the following:
1. Create a new branch for this feature on [https://github.com/responsible-ai-collaborative/mongodb-awesome-backup](https://github.com/responsible-ai-collaborative/mongodb-awesome-backup)
2. Create a new file `backup_snapshot.sh` that backup only the DB snapshot into a write-only AWS S3 bucket. We have to create a new S3 bucket under the same AWS account.
3. Create a new file `backup_snapshot_and_csv.sh` that backup the DB snapshot and also the CVS files with the filtered data (`{publish: false}`) into a public AWS S3 bucket. We can use the existing S3 bucket.
4. Change the current `backup.sh` file to just call the two scripts above.

**Comment by smcgregor** [comment]
I believe (3) is changing from posting snapshots to posting specific data. More specifically, all the data except some data that is more privileged/confidential. @kepae can describe the data separation.

@kepae The listing of data products in the AIID is another eventual feature flag. Also, the AWS account pre-dates the Responsible AI Collaborative. Maybe this is an opportunity for Brett to bring two simple S3 buckets under IaC management. @pdcp1 Brett is doing a lot of infra work with DSRI.

**Comment by pdcp1** [comment]
In summary, the PR opened reflects the following:

1. Create a new file `backup_full_snapshot.sh` that backup only the DB full snapshot into a write-only AWS S3 bucket.
We have to create a new S3 bucket under the same AWS account.
2. Create a new file `backup_filtered_data.sh` that backup the filtered DB snapshot and also the CVS files with the filtered data ({publish: false}) into a public AWS S3 bucket.
We can use the existing S3 bucket. This backup files should start publishing in https://incidentdatabase.ai/research/snapshots/
3. The `backup.sh` is deleted since is replaced by the two scripts above.

**Comment by kepae** [comment]
Thanks Pablo. I'll start getting the buckets setup.

After talking with Brett, he suggested we might also try to use [Cloudflare's R2 buckets which have an S3-style API](https://developers.cloudflare.com/r2/api/s3/api/), because we have a new Cloudflare account and are debating how (if) we use AWS. Ideally this should be superficial to change, now and in the future.

**Comment by pdcp1** [comment]
> Ideally this should be superficial to change, now and in the future.

Actually, in the way that this is currently implemented, we have to change the AWS packages that we use to upload files to S3 buckets in order to replace that code with the Cloudflare R2 packages needed. Assuming that there exist packages for that purpose.
Maybe it's a good idea to move forward with the current changes and open another issue to migrate it to Cloudflare.

**Comment by pdcp1** [comment]
@kepae I researched the Cloudflare R2 integration to upload the backup files and it looks like we can change our code to support R2 buckets.
The only thing that I need is the `CLOUDFLARE_API_TOKEN` (Token value), `CLOUDFLARE_ACCOUNT_ID` (Account ID) and the bucket names (ie: `aiid-public` and `aiid-private`)

**Comment by pdcp1** [comment]
@kepae I decided to change the code to use the `boto3` [R2 python library](https://developers.cloudflare.com/r2/examples/aws/boto3/) instead of the `wrangler` command since the `Object Read & Write` token permission works as expected in that way.

Please review this PR https://github.com/responsible-ai-collaborative/mongodb-awesome-backup/pull/4

As part of this PR, we have to add two Github Action secrets:
- `CLOUDFLARE_R2_ACCESS_KEY`
- `CLOUDFLARE_R2_SECRET_KEY`
And we can safely remove the old one `CLOUDFLARE_API_TOKEN`

**Comment by pdcp1** [comment]
@kepae I think we can close this issue now. Or maybe you want to share the snapshot generated with the other team first

**Comment by kepae** [comment]
Yes! 🎉
