### ISSUE TITLE
Discover – Improve Classification filtering UX

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2330]
Currently, taxonomy classifications are present as filter facets in the discover app. However, there are a few UX improvements to be made.

* The `Classifications` filter currently displays classifications in ascending alphabetical order of the taxonomy namespace, and within that, descending number of results by stringified field.
    * The user does not learn what taxonomies are available, up front.
    * Reasonably, the filter view does not show _all_ fields -- but without entering any data, it will only show a limited number of fields from `CSETv0`, potentially misleading the user to think these are the only classifications to filter by.

Potential improvements:
* At the top of the filter card, display a condensed multi-option selection list of taxonomy namespaces (e.g. CSETv0, CSETv1, GMF).
* When there is no search term, sort fields first by number of results for each field, _then_ sort by alphabetical string. Depends on if this yields a nice result in practice.)

This overlaps with goals from #2047. It might be better to pause #2047 until more expressive data is in the DB, and until then, beef up/improve the Discover interface (which could also benefit from https://github.com/responsible-ai-collaborative/aiid/issues/2292).
 
________

The current view:

<img width="666" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/4238598/452d8fa3-d168-435e-bfce-85bf89e929d9">

**Comment by cesarvarela** [comment]
Looks like instead of serializing each classification attribute, we should send the JSON structure as it is to Algolia:

Instead of sending 

`classifications: ['CSETv0:Intent:Accident']` 

We should send: 

`{classifications: [ {namespace: 'CSETv0', attributes: {'Intent' : 'Accident'}]}`.

https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/how-to/creating-and-using-nested-attributes/

It is not necessary to do this to accomplish some UI improvements; we can just `split` and `join` the strings back, but it limits us to only filter by namespace+attribute+value, instead of how the algolia example below allows filtering by tree branches and not just leaves, which would enable us to filter by namespace, namespace+ attribute, namespace+attribute+value, etc.

Algolia's Storybook tree filter example:  https://instantsearchjs.netlify.app/stories/js/?path=/story/refinements-hierarchicalmenu--default

Either way, I think the improvements should follow this tree-like design and should look something like this: 
<img width="790" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/86e70c24-a470-4714-8d4a-c7bb0943db67">

@kepae do you think we should do the refactor above? It might open us to other filtering options and be a good opportunity to migrate to the latest algolia version, which uses hooks: https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/#migrate-from-react-instantsearch-v6-to-react-instantsearch-v7, but it will be some work.

**Comment by lmcnulty** [comment]
See also https://github.com/responsible-ai-collaborative/aiid/issues/960.

**Comment by kepae** [comment]
(h/t to @lmcnulty for calling this out and suggesting tree-based filtering in August '22! 🎩 )

re: tree-based filtering: +1. Taxonomies are inherently hierarchical, and being able to filter by any level in the tree is a big win. Users could search "any incident with a CSETv1 classification", etc, which promotes exploring + finding more than pure leaf search.

re: UI: Very smooth.

* If selected facets are pulled out above to be readable (+1), how about including an "x" to dismiss on the left-hand side?
* What do you think about being able to add `NOT`-type query refinements, and pulling them out as red-colored facets? It would help with finding differences in taxonomy coverage. Then users could perform: `"CSETv0 : Near Miss : *" && NOT "CSETv1 : Harm Level : Near Miss"`

re: upgrade to Algolia React Instant Search v7: It looks like you previously had interest in this. If hooks make the code cleaner and easier to maintain, let's do it. Ideally doesn't have to happen at same time as upgrading the UI, so it can be delayed if needed.
https://github.com/responsible-ai-collaborative/aiid/blame/f5a033a3d6353b6bb6893eca01a28f8b0af96789/site/gatsby-site/src/components/discover/useSearch.js#L11

**Comment by cesarvarela** [comment]
@kepae, good to close this? Making the filters more prominent sounds like another issue.
