### ISSUE TITLE
Get Database Snapshots from the new Cloudflare R2 bucket

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#2374]
We should change the code of this page https://incidentdatabase.ai/research/snapshots/ to list all DB snapshots from the new Cloudflare R2 bucket instead of the current AWS S3.

- [x] Migrate all existing snapshot files from AWS S3 to Cloudflare R2
- [x] Change the code to retrieve the file list from Cloudflare R2
- [x] Update environment variables/secrets in AIID repo and Netlify

**Comment by kepae** [comment]
I'm downloading all existing backups and will manually copy them to the R2 buckets.
When we move this over, we can also squash https://github.com/responsible-ai-collaborative/aiid/issues/2017.

**Comment by smcgregor** [comment]
LMK if you need support on the downloading.

**Comment by kepae** [comment]
@pdcp1 backup history from S3 has been copied to `aiid-public-backups`, let me know if you need anything else and sorry for the delay!

**Comment by pdcp1** [comment]
Tested on Staging with Production Cloudflare R2 variables ✅ 
https://staging-aiid.netlify.app/research/snapshots/
Finally 🎉

**Comment by kepae** [comment]
Finally indeed 🎉 

One side effect – the dates of the downloads are read from the bucket file metadata and not inferred from the filename. This is logical, but means that the history of all snapshots I copied is "erased", as all items share the same date of Dec 8:

<img width="606" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/4238598/571338d8-b1d1-4b28-8211-17c67831f506">

We won't block on this, but this is confusing for a user looking for a certain date.

Perhaps we should just remove the human-readable string in the front, since we display the filename containing the date string:
`<filename> · <size>`

What do you think, @pdcp1?

(also, I updated the production Netlify values as well, so this can go to prod)

**Comment by pdcp1** [comment]
@kepae You're right about the dates, I didn't notice the `2023-12-08` file cases.
I prefer to keep the human-readable string date, considering I'm unsure if everyone will notice that the date is "encoded" in this 14-digit string.

Something easy to do is to parse the 14-digit string from the file name and convert it to a Date. Doing that, both dates will match.

PS: Thanks for updating the Production Netlify values in advance!
I have to consider the timezone but it's not a big deal.
