### ISSUE TITLE
Fetching info from Washington Post articles

### ISSUE THREAD

**Issue by datherton09** [responsible-ai-collaborative/aiid#2421]
Low priority here, but it could expedite incident reporting if "fetch info" worked for Washington Post articles (which does quite a bit of incident/issue reporting). I currently have to manually input all information from WaPo articles, which isn't a big deal, but it does add more time to the process. No rush, though -- thank you!
-d

**Comment by lmcnulty** [comment]
@kepae 

When I run the server locally from the master branch, it works.

When I try to fetch a Washington post article from https://incidentdatabase.ai/apps/submit, it fails with a 502. I'm not sure if that's the same error as before. To diagnose I think I need to add an error response with the debugging information rather than just rely on the default.

![image](https://github.com/responsible-ai-collaborative/aiid/assets/25443411/4824f1ef-3d68-4cce-b565-45691103a5b3)

**Comment by kepae** [comment]
I wasn't able to reproduce this, going to close but we can re-open if needed.
