### ISSUE TITLE
Ingested many reports but no update

### ISSUE THREAD

**Issue by datherton09** [responsible-ai-collaborative/aiid#2429]
Hi all -- on Saturday afternoon, I ingested a bunch of new reports into the system, but the system doesn't seem to have cycled through an update since then. Not sure if that's a glitch or if it's the result of some tinkering on your end, but thought I'd flag it. Thanks!
-d

**Comment by kepae** [comment]
At the moment, we've temporarily paused the builds and updated deployments of the website while we address an issue with duplicate email notifications. See: https://github.com/responsible-ai-collaborative/aiid/issues/2404
Since these notifications are triggered in the build process, we're addressing that first, and then will re-enable the regular updates to the site. Sorry for the trouble!
