### ISSUE TITLE
Suggestion: Change "Latest Incident Report" to Incident ID rather than individual news report?

### ISSUE THREAD

**Issue by datherton09** [responsible-ai-collaborative/aiid#2563]
What would you all think of changing the "Latest Incident Report" that appears on the main page from the latest news report within an incident ID to the incident ID itself? This might be one of the ways to perform some slight distancing from journalistic bias issues. For example, the latest report (whose title is "Microsoft says its AI is safe. So why does it keep slashing people’s throats?") copies the sensationalistic tone of the reporting to our own work, placing it front and center for visitors to our site. Small adjustments that place our own titling at the forefront may be a way to mitigate this.

**Comment by kepae** [comment]
This is a great suggestion, I've thought about this as well. In effect, we don't have direct control or context on the first thing that pops up on our page, beyond having chosen to ingest the report (and we shouldn't avoid ingesting reports for failing to look sensible on the home page).

Providing context: perhaps we could do something that combines both the Incident ID + title that AIID has created, as well as surfacing the original report language. The report is where we source the image from, which feels important to present alongside the source, IMHO.

Some ideas:
* place incident id + title above card, either across the whole card or above the text portion
* place incident id+ title below card
* place just incident ID somewhere?

![Board(1)](https://github.com/responsible-ai-collaborative/aiid/assets/4238598/ea06da93-30be-4cc1-9b08-b42f461a4233)

WDYT?

**Comment by Janetbananet** [comment]
This is an interesting point! I agree both with Danny's instincts on distancing from journalistic bias (that it feels like the prominence given to the latest report may have the risk of copying a sensationalistic tone the way it's presented), and I also see Kevin's point about the issue with making sure the report image is clearly credited to the report vs any assumptions it was created by the Editors. 

A question about the intent of this section on the website: do we need that image? Would a carousel of recent incidents vs reports be more along the lines of what our primary website visitor would be interested in?

If indeed we want to keep the current design with a prominent latest **report**,  then I like the look of the first version @kepae has above (Incident ID + title across a portion of the card). But @datherton09 may have a different idea on it.

**Comment by datherton09** [comment]
Thank you, @kepae and @Janetbananet ! Much appreciated. Regarding the questions (if we need an image and regarding the carousel), I don't have ready answers at this point -- I'd have to think about them more! But in the meantime, I agree with Janet that the first one looks good. :)

**Comment by lmcnulty** [comment]
Some things to containerize the report:

- Put a border around it
- Use quotation around the title

I think we could put the incident title either as a full card header...

![image](https://github.com/responsible-ai-collaborative/aiid/assets/25443411/ba01ed3e-46df-4ae7-83a5-b0419fe91e7b)

<img height="400" src="https://github.com/responsible-ai-collaborative/aiid/assets/25443411/c2570b58-242d-4609-85ee-7926ffa1e2de" />

Or above just above the report title:

![image](https://github.com/responsible-ai-collaborative/aiid/assets/25443411/2d8d35fd-b4b7-4cc0-897d-74d6121e4d5a)

<img height="400" src="https://github.com/responsible-ai-collaborative/aiid/assets/25443411/1aa51f2f-97b9-4e0d-a606-813c7c13ee30"/>

It's also not obvious to me that we need to display the latest report rather than latest incident. We could just use more or less same design we have now but with the incident title and description instead of the report title and truncated text.

![image](https://github.com/responsible-ai-collaborative/aiid/assets/25443411/b75a59fb-cc19-4e2a-875d-27515639eb7f)

**Comment by kepae** [comment]
Fantastic study, @lmcnulty. Personally, I'm in favor of keeping the Incident ID visible somewhere – it's what shouts that we're a database and indexing things, not just promoting articles.

And as you suggest and @datherton09 mentioned in the original post, we could just use the incident title. (I think @jphall663 was in favor of keeping the report titles themselves?)

I'll bring this up in the next product meeting (next week), and we'll come up with the "final" decision there and get moving.

**Comment by kepae** [comment]
@lmcnulty we got some feedback, and it looks like the preferred option is your second display -- rendering the Incident number and title above the boxed report title. Please consider this ready for work. :-)

**Comment by kepae** [comment]
We're live!
