### ISSUE TITLE
Test failures – Discrepancy between incident page count and GraphQL endpoint count

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#2615]
This has been happening in multiple environments:

https://github.com/responsible-ai-collaborative/aiid/actions/runs/7736942933/job/21116835017#step:7:481

https://github.com/aiidtest/aiid/actions/runs/7750886781/job/21138036135#step:7:285

https://github.com/responsible-ai-collaborative/aiid/actions/runs/7780225084/job/21229566391

Current guesses:

- something is being cached somewhere
- Gatsby's graphql endpoint returns a different number of incidents vs. Atlas graphql endpoint

**Comment by cesarvarela** [comment]
It's been a while since this last happened.

**Comment by kepae** [comment]
Unfortunately I think we're still seeing this error, happened in the past two automatic cron workflows to re-build prod:
https://github.com/responsible-ai-collaborative/aiid/actions/runs/8023221999

I manually pushed today to get updates, skipping the cache.

**Comment by kepae** [comment]
Could be a coincidence still, but manual dispatches succeed where automatic ones are failing. All recent failures are due to this same test failure. 

<img width="1183" alt="Screenshot 2024-02-27 at 11 59 29 AM" src="https://github.com/responsible-ai-collaborative/aiid/assets/4238598/5dff5711-74c6-4748-a0a9-0e515864b31b">

All manual runs were set to skip the cache, but the production job does that too right now.
https://github.com/responsible-ai-collaborative/aiid/blob/152c5c048e3cca30b6f571a25d6e155aa829a750/.github/workflows/production.yml#L14

**Comment by cesarvarela** [comment]
The issue is that for scheduled deploys, since the commit sha doesn't change, so it uses the first cached build of that sha and any new incident after that first build is not there obviously 💥 

I'll update the workflows to take this into account, most probably checking that if it is an scheduled run, a new cache key needs to be created.

<img width="965" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/eee91d0d-2881-411a-82da-0fd24a943e32">

**Comment by kepae** [comment]
LGTM now!
