### ISSUE TITLE
Toast error message overflow

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#2649]
### Steps to reproduce:

1. https://incidentdatabase.ai/apps/submit/
2. Enter `https://www.washingtonpost.com/technology/2023/04/05/chatgpt-lies/` in the Report Address field and click `Fetch Info` button
3. An error message is displayed out of the toast popup boundaries

<img width="1784" alt="Screenshot 2024-02-19 at 16 59 30" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/523f027e-fa40-4c2e-8b5b-84ce1b187008">

**Comment by clari182** [comment]
@pdcp1 It looks like it's that website that sometimes takes longer than 10 seconds (axios limit) to respond. Sometimes it takes less. But I did find another issue while testing this. If there's an error like that one and you fetch again, it doesn't really fetch but looks for the results in the cookies. Since that result is corrupted due to the prior error it's not re-fetching as it should. I'll assign that one to myself.
