### ISSUE TITLE
Implicated systems field required

### ISSUE THREAD

**Issue by datherton09** [responsible-ai-collaborative/aiid#2982]
Hi all, I'd like to request the inclusion of an implicated systems field in the submission form. I'm not sure how big of a change this might introduce into the system, but I am noticing that the lack of this field presents several problems -- either we're excluding the name of the implicated system or we're having to make decisions to gesture toward the implicated system in either the developer or deployer field. No rush, but something to consider! Thanks. -d

**Comment by kepae** [comment]
This is great, I'm glad to hear it is an editor need we now have :-). We definitely want to move towards beginning to name and track particular systems. We don't want to shoe-horn this indirectly with the deployer, developer, or affected stakeholder entities.

The bottom line for us is we will start using the existing entities collection to also contain AI systems or components, in addition to organizations and other actors as currently done. It's on us to develop structure.

I like the term `implicated_system` for the relationship between incident report and AI system -- partially because it's generic in both allegation and the notion of what is "AI."

For development, I'd suggest adding an `implicated_systems` array to the submission and incident object documents.
- [ ] I would start with adding the field to incident objects, 
- [ ] allowing editors to edit the implicated system in the editing interface as with alleged deployers and developers,
- [ ] then after some experience curating these entities, adding this field as information that can be submitted in the submission form with reports.

@datherton09 would that work for you? 

NB: We will need to develop some flexible way of grouping and organizing related systems that makes sense for aggregation and analysis. For example, being able to implicate a particular version of an AI model versus the _family_ of models (e.g. GPT-4 Turbo model vs. ChatGPT system in general). This is where we will start to curate entity-entity relationships:
* #2975

**Comment by datherton09** [comment]
Works for me! :)
