### ISSUE TITLE
Live `FindIncident` query failing; new incident emails arriving before Netlify deploy completes, citation page is 404

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2990]
I just received the email notifications for new incidents. However, at the time of writing, the citation pages for them are unavailable on incidentdatabase.ai. Further, the live incident fallback doesn't appear to retrieve from the DB dynamically, resulting in a 404/not found. I can reproduce this and find that it's an issue with the `FindIncident` query:

```graphql
{
  "errors": [
    {
      "message": "Variable \"$query\" got invalid value \"748\" at \"query.incident_id\"; Int cannot represent non-integer value: \"748\"",
      "locations": [
        {
          "line": 1,
          "column": 20
        }
      ]
    }
  ]
}
```

Hucking it over to you @cesarvarela for consistency, as this showed up with other API issues, e.g. https://github.com/responsible-ai-collaborative/aiid/issues/2987

Sounds like we need some more test coverage for API migrations. :-)
(Or we need to trust our test suite again when the playwright migration finishes 🤡 )

**Comment by pdcp1** [comment]
I found myself in the same situation when I received the new incident emails yesterday evening.
FYI, the query error can be reproduced at any time on Staging or Production by navigating to a non-existing Incident (like https://incidentdatabase.ai/cite/800)

**Comment by pdcp1** [comment]
After merging #2993 into Staging this issue was resolved.

I just created a new Incident on Staging and it loads fine ✅ 
https://staging-aiid.netlify.app/cite/756

Also, if I try to access a non-existing Incident (e.g: https://staging-aiid.netlify.app/cite/1000 ) the graphql call doesn't fail with an error, it just returns a null (as expected) and displays an `Incident 1000 not found` message ✅
