### ISSUE TITLE
Images 404ing

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#723]
Two images on incident 66 are 404ing.

<img width="480" alt="Screen Shot 2022-06-21 at 10 13 45 PM" src="https://user-images.githubusercontent.com/64780/174948812-8650ebfa-a85a-4533-a3bd-cae887d8b177.png">

<img width="862" alt="Screen Shot 2022-06-21 at 10 12 48 PM" src="https://user-images.githubusercontent.com/64780/174948725-b7315b23-7917-4f07-a152-6493c96c840d.png">

**Comment by lmcnulty** [comment]
@clari182 Hey, I started on this earlier today and think I have a solution in #792, although perhaps you've found a better solution. I'm sorry if I stepped on your toes – I should have self-assigned this first.

**Comment by clari182** [comment]
Hey @lmcnulty ! Sounds good to me! I haven't actually reached a specific fix for this, I only worked on Migrations to fix those 2 specific images on the DB. So I think we're both g2g on this.

**Comment by lmcnulty** [comment]
In staging, these images now show the fallback instead of the broken image icon. Some the images in question exist at the original source, but won't load through Cloudinary. Changing the way we escape URLs will sometimes cause a previously broken image to load, but then break others. I'm not sure if there's a solution for this. The initial problem is solved, so I'm going to close this. Related issues can be opened and prioritized separately.
