### ISSUE TITLE
Separate Documentation Elements of Site

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#851]
Currently the site is designed around documentation. While we need to maintain proper documentation of the applications and processes, we should separate the design considerations of docs and the presentation of the data in the database. The first step on this is a Figma (or similar) design mockup of the site navigational structure and how docs+database apps fit together.

**Comment by lmcnulty** [comment]
I think we can put most of the documentation under the "About" section of our navigation hierarchy, then split the apps between (1) those that help people find and examine the incidents in the database and (2) those that are helpful to those adding incidents to the database or otherwise participating.

I imagine the hierarchy of the navigation being structured something like this:

- Welcome to the AIID
- About
  - People (Board of directors, collaborators, transcluded leaderboard)
  - Incident Report acceptance criteria
  - Roadmap (database roadmap → roadmap)
    - In Development
    - Future
    - Delivered
    - Initial collection methodology
  - Researcher Guide – I think this should be limited to things that unlikely to be relevant to non-researchers, like citation information. Its current child pages I think can go elsewhere in the hierarchy.
  - Taxonomies
- Blog (Aiid Blog → Blog)
- Explore Collection
  - Discover Incidents
  - TSNE Visualization – This is interesting enough that it could get its own page.
  - Wordcounts
  - Taxonomy Graphs – We currently have pie charts for items in the CSET database, but https://incidentdatabase.ai/taxonomy/cset, but to get to them you have to go to "taxonomies" in the sidebar, then pick "CSET", then scroll past a couple paragraphs of text. I think it would be nice to have the graphs centered on their own page and link to the details on the taxonomy from there.
- Participate
  - Submit Incident Reports
  - Leaderboard
  - Submission Queue
  - Flagged Incidents
  - Classifications View

**Comment by smcgregor** [comment]
* `TSNE Visualization – This is interesting enough that it could get its own page.` Agree. It could be a "summary" (this is what we have been calling pages that are reports on the data in the database) or potentially an "app" (these generally have more dynamic interaction with the database such as read and write capabilities).
* `Taxonomy Graphs – We currently have pie charts for items in the CSET database, but https://incidentdatabase.ai/taxonomy/cset, but to get to them you have to go to "taxonomies" in the sidebar, then pick "CSET", then scroll past a couple paragraphs of text. I think it would be nice to have the graphs centered on their own page and link to the details on the taxonomy from there.` How about a modal, or a collapsed documentation area linked at the top of the CSET taxonomy page? Most people will not read context, but we can conditionally provide it and present only a single sentence to the effect of, "this is a taxonomy as applied by CSET..."
* The ordering you have also places the documentation elements above the exploration elements, and it should likely be the reverse.

How about we put a little more in the footer as well?

FOOTER (items that people often look for, but are not necessarily at the top level navigation)

* Blog (also include a prominent component on the landing page)
* Organization (single page with a new Organizational statement, People,  collaborators, leaderboard component, roadmap, )
* (Add OSI logo or similar)

SITE NAV

- Welcome to the AIID
- Explore Collection (These are what we have called "summaries" before and are where we want to direct most users)
  - Discover Incidents
  - TSNE Visualization
  - Wordcounts
  - Taxonomies (Classifications View should be linked from here)
- Submissions (This heading needs new content, but the sub content exists)
  - Submit Incident Reports
  - Leaderboard
  - Review Queue
  - Flagged Incidents
- About
  - Incident Report acceptance criteria
  - Researcher Guide (include Initial collection methodology)
  - Blog
  - Organization (Needs new content)

I like this because people generally explore first, then submit, and if at some point they want to read about the site it exists at the end or in the footer and they can find it. Thoughts?

This is also orthogonal to how the navigational structure is presented. Maybe we should add a few sites as design inspiration and mimic their affordances?
