### ISSUE TITLE
Social Share Buttons

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#856]
People should be able to share/tweet/like content on the site.

Initiative #845

**Comment by smcgregor** [comment]
I believe the priority on this should be:

1. A "Share" button on the citation pages (e.g., https://incidentdatabase.ai/cite/244 ). In priority order, we should support sharing to Twitter, LinkedIn, Email, Facebook, (then everything else)
2. When users submit an incident report, we could also optionally give the user the option of sharing their submission, but I think that is likely more work than it is worth

Note that I really dislike these buttons because they are tracking users on our website. I prefer solutions like [these](https://panzi.github.io/SocialSharePrivacy/) because they have better privacy properties.

CC @pdcp1

**Comment by pdcp1** [comment]
I was looking at [this component](https://panzi.github.io/SocialSharePrivacy/) that @smcgregor suggested and it seems like it could work. My concern with this component is that its [Github repo](https://github.com/panzi/SocialSharePrivacy) is quite abandoned. It doesn't have changed since July 2019.

In another hand, I was researching about privacy on this type of sharing buttons, and I found this [post](https://www.tunnelbear.com/blog/why-we-created-our-own-social-media-buttons-on-our-website/) from TunnelBear that suggest creating our own simple share buttons using the share URL for each social network.
In that way, we can be sure that we are not going to have any privacy issue.

Any thoughts or suggestions? 

The code it will looks like this:
```
<div>
  <button onClick={() => {window.open(`https://twitter.com/intent/tweet?text=${metaTitle}&url=${canonicalUrl}`, 'twitter-share', 'width=550,height=235');return false;}}>
    Twitter
  </button>
  <button onClick={() => {window.open(`https://www.facebook.com/sharer/sharer.php?u=${canonicalUrl}`, 'facebook-share','width=580,height=296');return false;}}>
    Facebook
  </button>
  <button onClick={() => {window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${canonicalUrl}`, 'linkedin-share','width=600,height=300');return false;}}>
    LinkedIn
  </button>
</div>
```

cc: @cesarvarela @clari182 @lmcnulty

**Comment by lmcnulty** [comment]
I agree strongly that we should try to find a privacy-preserving solution. I think libraries like Social Share Privacy are intended for cases where it's desirable to interface with a social media site without opening it in a new tab, e.g. "liking" something. If we only need sharing, I think the suggestion of using buttons with share URLs would be the best option.

**Comment by smcgregor** [comment]
I am also good with the suggested path forward providing the UX on mobile holds up.

**Comment by pdcp1** [comment]
Regarding the second part of this issue:

> When users submit an incident report, we could also optionally give the user the option of sharing their submission, but I think that is likely more work than it is worth

We can't prompt the share option as soon as the user submits a report since the incident is not published yet, so there is no URL to share until somebody reviews and approves it.
What we can do is add the option to share the incident when the reviewer approves the report.

**Comment by pdcp1** [comment]
I added a link to the incident to the Submission Review toast message, so the user can click and see the incident page and share it.
This is an easy and clear way to allow the user to share the new report associated with an existing incident.

**This is the toast for a report associated with an existing incident:**

<img width="373" alt="Screen Shot 2022-08-03 at 21 41 19" src="https://user-images.githubusercontent.com/6564809/182739385-69c4d5b9-eca4-4ce3-ac77-08da9bf41d90.png">

**This is the toast for a report just approved that creates a new incident:**

<img width="367" alt="Screen Shot 2022-08-03 at 21 40 21" src="https://user-images.githubusercontent.com/6564809/182739470-0aa39cc5-e371-4ef5-bb04-9c7d5728b9b4.png">
