### ISSUE TITLE
Add descriptive placeholders to developer, deployer, harmed parties fields

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#984]
The fields added with #805 should use placeholders that better clarify what those fields mean. We could use obviously-made-up examples:

"Alleged developer of AI system" → "E.g. PoodleSoft Canine Identification Technologies LLC."
"Alleged deployer of AI system" → "E.g. Clayton County Dog Catcher"
"Alleged harmed or nearly harmed parties" → "E.g. Dogs"

Those might sound too silly, though. We could also just use textual descriptions of what the field means:

"Alleged developer of AI system" → "Who made the technology in question?"
"Alleged deployer of AI system" → "Who caused harm by using it?"
"Alleged harmed or nearly harmed parties" → "Who was hurt?"

_Originally posted by @lmcnulty in https://github.com/responsible-ai-collaborative/aiid/issues/805#issuecomment-1219882692_

**Comment by smcgregor** [comment]
I like the second set. Slight tweaks:

"Alleged developer of AI system" → "Who made the technology involved in the incident?"
"Alleged deployer of AI system" → "Who employed or was responsible for the technology?"
"Alleged harmed or nearly harmed parties" → "Who experienced negative impacts?"

I am good with most messages here, but we should not have the word "caused" since that doesn't cover some cases, and we similarly shouldn't use the word "hurt".

**Comment by LKchemposer** [comment]
A minor tweak:

Developer: "Who created or built the technology involved in the incident?"
